apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: finance-service
  template:
    metadata:
      labels:
        app: finance-service
    spec:
      containers:
      - name: finance-service
        image: <ECR_URL>/finance-service:latest
        ports:
        - containerPort: 6100
---
apiVersion: v1
kind: Service
metadata:
  name: finance-service
spec:
  selector:
    app: finance-service
  ports:
  - port: 6100
    targetPort: 6100
  type: ClusterIP
